apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: grafana-app
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: http
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana-container
        image: grafana-image
        ports:
        - containerPort: 3000
        imagePullPolicy: Never