# /var/run/docker.sock:/var/run/docker.sock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb-container
        image: influxdb-image
        imagePullPolicy: Never
        volumeMounts:
          - name: influxdb-volume
            mountPath: /var/lib/influxdb
          - name: dockersock
            mountPath: "/var/run/docker.sock"
        ports:
        - containerPort: 8086
        # livenessProbe:
        #   exec:
        #     command:
        #       - sh
        #       - /health.sh
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: dockersock
          hostPath:
           path: /var/run/docker.sock  
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb-app

  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  resources:
    requests:
      storage: 300Mi
  accessModes:
    - ReadWriteOnce