apiVersion: v1
kind: Service
metadata:
  name: edge-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: edge-service
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
    name: https
  - port: 80
    targetPort: 80
    name: http
  - port: 22
    targetPort: 22
    name: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
spec:
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - name: edge-container
        image: edge-service
        imagePullPolicy: Never
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
        - containerPort: 22
          name: ssh