apiVersion: v1
kind: Service
metadata:
  name: php-my-admin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app:  php-my-admin-app
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  phpmyadmin
spec:
  selector:
    matchLabels:
      app:   php-my-admin-app
  template:
    metadata:
      labels:
        app:  php-my-admin-app
    spec:
      containers:
      - name: php-my-admin-container
        image: php-my-admin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
