apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  selector:
    app: mysql-db-app
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
spec:
  selector:
    matchLabels:
      app:  mysql-db-app
  template:
    metadata:
      labels:
        app:  mysql-db-app
    spec:
      containers:
      - name: mysql-db-container
        image: mysql-db-image
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
             - sh
             - /health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql/
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql