apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app:  wordpress-app
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wordpress
spec:
  selector:
    matchLabels:
      app:   wordpress-app
  template:
    metadata:
      labels:
        app:  wordpress-app
    spec:
      containers:
      - name: wordpress-container
        image: wordpress-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
