apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps-app
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    name: ftp
  - port: 2101
    targetPort: 2101
    name: ftp1
  - port: 2100
    targetPort: 2100
    name: ftp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-volume
  labels:
    app: ftps-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app:  ftps-app
  template:
    metadata:
      labels:
        app:  ftps-app
    spec:
      containers:
      - name: ftps-container
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp
        - containerPort: 2101
          name: ftp1
        - containerPort: 2100
          name: ftp2
        volumeMounts:
          - name: ftps-volume
            mountPath: /opt/remote
      volumes:
      - name: ftps-volume
        persistentVolumeClaim:
          claimName: ftps-volume